# Generated by Django 4.1 on 2022-09-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.IntegerField(verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('advisory_status', models.CharField(max_length=10, verbose_name='Estado Asesor')),
            ],
        ),
        migrations.CreateModel(
            name='GerenteDeCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.IntegerField(choices=[(1, 'Villa de Leyva'), (2, 'Lago de Tota'), (3, 'Hacienda Napoles'), (4, 'Desierto de la Tatacoa'), (5, 'Eje Cafetero'), (6, 'Medellin y Guatapé'), (7, 'Santander'), (8, 'Cartagena'), (9, 'Guajira'), (10, 'San Andres'), (11, 'Santa Marta'), (12, 'Amazonas'), (13, 'Bahía Solano'), (14, 'Capurgana'), (15, 'Ciudad Perdida'), (16, 'Caño Cristales'), (17, 'Deportes Extremos Nimaima'), (18, 'Nevado del Cocuy'), (19, 'Cuatrimotos Villa de Leyva'), (20, 'Parapente Villavicencio')])),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor venta')),
                ('advisory_commission', models.IntegerField(verbose_name='Comisión')),
                ('commission_to_pay', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Comisión a pagar')),
                ('commission_status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagada'), (3, 'Anulada')], default=1, verbose_name='Estado de comisión')),
                ('Asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terratur_app.asesor')),
            ],
        ),
        migrations.AddField(
            model_name='asesor',
            name='GerenteDeCuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terratur_app.gerentedecuenta'),
        ),
    ]
